w4/w4d2-3/cat_app/config/routes.rb
Rails.application.routes.draw do
  root to: "cats#index"
  resources :cats, except: [:destroy]
  resources :cat_rental_requests do
    patch "approve", to: "cat_rental_requests#approve"
    patch "deny", to: "cat_rental_requests#deny"
  end

  resources :users, only: [:new, :create]
  resource :session, only: [:new, :create, :destroy]
end

w4/w4d2-3/cat_app/app/models/cat.rb
class Cat < ActiveRecord::Base
  COLORS = ["brown", "white", "black", "yellow", "grey", "blue", "rainbow"]
  belongs_to :owner, class_name: "User", foreign_key: :user_id
  validates :birth_date, :name, presence: true
  validates :color, inclusion: { in: COLORS, message: "%{value} is invalid" }
  validates :sex, inclusion: { in: %w(M F), message: "%{value} is invalid" }

  has_many(
    :rental_requests,
    class_name: "CatRentalRequest",
    foreign_key: :cat_id,
    primary_key: :id
  )

  has_many :renters, through: :rental_requests, source: :renter

  def age
    # Use SQL to do this later
    Integer((Time.now - birth_date.to_time) / 31536000)
  end

end

w4/w4d2-3/cat_app/app/controllers/cats_controller.rb
class CatsController < ApplicationController
  #before_action :logged_in?
  before_action :own_cat?, only: [:edit, :update, :destroy]

  def index
    col = params[:order_by] || 'name'
    order = params[:order] || 'asc'

    @cats = Cat.all.order( col => order)
    render  :index
  end

  def show
    @cat = Cat.find(params[:id])
    render :show
  end

  def new
    @cat = Cat.new
    render :new
  end

  def create
    @cat = Cat.new(cat_params)
    @cat.owner = current_user

    if @cat.save
      redirect_to @cat
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @cat = Cat.find(params[:id])
    render :edit
  end

  def update
    @cat = Cat.find(params[:id])
    if @cat.update(cat_params)
      redirect_to @cat
    else
      render :edit, status: :unprocessable_entity
    end
  end

  private
    def cat_params
      params.require(:cat).permit(:name, :description, :sex, :birth_date, :color, :image_url)
    end

    def own_cat?
      cat = Cat.find(params[:id])
      unless cat.owner == current_user
        redirect_to cats_path
      end
    end
end

w4/w4d2-3/cat_app/app/helpers/cats_helper.rb
module CatsHelper
  def toggle_order
      params[:order] == "asc" ? "desc" : "asc"
  end
end

w4/w4d2-3/cat_app/app/views/cats/_form.html.erb
<% request_method = cat.persisted? ? 'patch' : 'post' %>
<% action = cat.persisted? ? "/cats/#{cat.id}" : "/cats" %>
<% submit_value = cat.persisted? ? 'Update Cat!' : 'New Cat!' %>

<% if cat.errors.any? %>
<ul>
  <% cat.errors.full_messages.each do |msg| %>
  <li>
    <%= msg %>
  </li>
  <% end %>
</ul>
<% end %>
<form action="<%= action %>" method="post" class="form-horizontal">
  <input type="hidden" name="_method" value="<%= request_method %>">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>"> 
  <div class="form-group">
    <label for="cat_name" class="col-md-2 control-label">Name</label>
    <div class="col-md-6">
      <input type="text" name="cat[name]" value="<%= cat.name %>" id="cat_name">
    </div>
  </div>

  <div class="form-group">
    <label for="cat_birth_date" class="col-md-2 control-label">Birthday</label>
    <div class="col-md-6">
      <input type="date" name="cat[birth_date]" value="<%= cat.birth_date %>" id ="cat_birth_date">
    </div>
  </div>

  <div class="form-group">
    <label for="cat_color" class="col-md-2 control-label">Color</label>
    <div class="col-md-6">
      <select name="cat[color]" id="cat_color">
        <% Cat::COLORS.each do |color| %>
        <option value="<%= color %>" <%= "selected" if color == cat.color %>>
          <%= color %>
        </option>
        <% end %>
      </select>
    </div>
  </div>

  <div class="form-group">
    <label for="cat_sex" class="col-md-2 control-label">Sex</label>
    <div class="col-md-6">
      <select name="cat[sex]" id="cat_sex">
        <% ['M', 'F'].each do |sex| %>
        <option value="<%= sex %>" <%= "selected" if sex == cat.sex %>>
          <%= sex %>
        </option>
        <% end %>
      </select>
    </div>
  </div>

  <div class="form-group">
    <label for="cat_desciption" class="col-md-2 control-label">Description</label>
    <div class="col-md-6">
      <input type="textarea" name="cat[description]" value="<%= cat.description %>" id="cat_id">
    </div>
  </div>

  <div class="form-group">
    <label for="cat_image_url" class="col-md-2 control-label">Image Url</label>
    <div class="col-md-6">
      <input type="text" name="cat[image_url]" value="<%= cat.image_url %>" id="cat_image_url">
    </div>
  </div>

  <div class="form-group">
    <div class="col-md-6 col-md-offset-2">
      <input type="submit" class="btn btn-default" value="<%= submit_value %>">
    </div>
  </div>
</form>

w4/w4d2-3/cat_app/app/views/cats/edit.html.erb
<h1>Edit Cat</h1>

<%= render "form", cat: @cat %>
<%= link_to "Back to the cat", cat_path(@cat) %>

w4/w4d2-3/cat_app/app/views/cats/index.html.erb
<h1>All Cats</h1>
<table class="table table-bordered table-striped">
  <thead>
    <tr>
      <th>Photo</th>
      <th><%= link_to "Name", cats_path(order_by: :name, order: toggle_order), method: "get" %></th>
      <th>Birth Date</th>
      <th><%= link_to "Age", cats_path(order_by: :birth_date, order: toggle_order), method: "get" %></th>
      <th>Color</th>
      <th>Sex</th>
      <th>Description</th>
    </tr>
  </thead>
  <tbody>
    <% @cats.each do |cat| %>
    <tr>
      <td><a href="<%= cat_path(cat) %>"><img src="<%= cat.image_url %>" height=150></a></td>
      <td><%= link_to cat.name, cat %></td>
      <td><%= cat.birth_date %></td>
      <td><%= cat.age %></td>
      <td><%= cat.color %></td>
      <td><%= cat.sex %></td>
      <td><%= cat.description %></td>
    </tr>
    <% end %>
  </tbody>
</table>
<% unless current_user.nil? %>
  <a href="/cats/new" class="btn btn-primary">New Cat</a>
  <a href="/cat_rental_requests/new" class="btn btn-primary">Rent a Cat</a>
<% end %>

w4/w4d2-3/cat_app/app/views/cats/new.html.erb
<h1>New Cat</h1>
<%= render "form", cat: @cat %>
<%= link_to "Back to All Cats", cats_path %>

w4/w4d2-3/cat_app/app/views/cats/show.html.erb
<h1>Cat</h1>

<table class="table table-bordered table-condensed">
  <thead>
    <tr>
      <th>Photo</th>
      <th>Name</th>
      <th>Birth Date</th>
      <th>Age</th>
      <th>Color</th>
      <th>Sex</th>
      <th>Description</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><img src="<%= @cat.image_url %>"  height=150></td>
      <td><%= @cat.name %></td>
      <td><%= @cat.birth_date %></td>
      <td><%= @cat.age %></td>
      <td><%= @cat.color %></td>
      <td><%= @cat.sex %></td>
      <td><%= @cat.description %></td>
    </tr>
  </tbody>
</table>

<h3>Rent Requests</h3>
<ol>
  <% @cat.rental_requests.order(:start_date).each do |req| %>
    <li>
      <%= req.start_date %> ~ <%= req.end_date %>
      | Status: <span><%= req.status %> <%= req.renter.user_name %></span>
      <% if req.pending? && @cat.owner == current_user %>
        <%= button_to "approve", cat_rental_request_approve_path(req), method: :patch  %>
        <%= button_to "deny", cat_rental_request_deny_path(req), method: :patch %>
      <% end %>
    </li>
  <% end %>
</ol>

<%= link_to "All Cats", cats_path %>
<% if @cat.owner == current_user %>
  <%= link_to "Edit", edit_cat_path(@cat), class: 'btn btn-primary' %>
<% end %>