w5/w5d1/objective_setter_app/config/routes.rb
Rails.application.routes.draw do
  root to: "goals#index"
  resources :users, only: [:new, :create, :index, :show] do
    resources :comments, only: [:new]
  end
  resource :session, only: [:new, :create, :destroy]
  resources :goals do
    resources :comments, only: [:new]
    patch "complete", on: :member
  end
  resources :comments, only: [:create]
end

w5/w5d1/objective_setter_app/app/models/comment.rb
class Comment < ActiveRecord::Base
  validates :body, :user_id, :commentable_id, :commentable_type, presence: true
  belongs_to :commentable, polymorphic: true
  belongs_to(
    :commenter,
    class_name: "User",
    foreign_key: :user_id,
    primary_key: :id
    )

end

w5/w5d1/objective_setter_app/app/models/concerns/commentable.rb
module Commentable
  extend ActiveSupport::Concern

  included do
    has_many :comments, as: :commentable
  end
end

w5/w5d1/objective_setter_app/app/models/goal.rb
class Goal < ActiveRecord::Base
  include Commentable
  
  GOAL_TYPES = ["public", "private"]
  validates :title, :goal_type, :user_id, presence: true
  validates :goal_type, inclusion: { in: GOAL_TYPES}

  belongs_to :user

  def complete!
    self.toggle!(:completed)
  end
end

w5/w5d1/objective_setter_app/app/models/user.rb
class User < ActiveRecord::Base
  include Commentable

  attr_reader :password
  validates :username, :session_token, :password_digest, presence: true
  validates :password, length: { minimum: 6, allow_nil: true}

  has_many :goals
  has_many :authored_comments, class_name: "Comment", foreign_key: :user_id

  before_validation(on: :create) do
    self.session_token = SecureRandom::hex
  end

  def self.find_by_credentials(username, password)
    u = User.find_by(username: username)
    return nil if u.nil? || !u.is_password?(password)
    u
  end

  def password=(password)
    @password = password

    self.password_digest = BCrypt::Password.create(password)
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def reset_session_token!
    self.session_token = SecureRandom::hex
    self.save
    self.session_token
  end
end

w5/w5d1/objective_setter_app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= User.find_by(session_token: session[:session_token])
  end

  def logged_in?
    !!current_user
  end

  def log_in!(user)
    session[:session_token] = user.reset_session_token!
  end

  def log_out!
    current_user.reset_session_token!
    session[:session_token] = nil
  end

  def ensure_login
    redirect_to new_session_path unless logged_in?
  end
end

w5/w5d1/objective_setter_app/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @comment = Comment.new(comment_params)
    @comment.commenter = current_user

    model_name = @comment.commentable_type
    model_id = @comment.commentable_id
    @object = model_name.capitalize.constantize.find(model_id)
    if @comment.save
      redirect_to @object
    else
      flash[:errors] = @comment.errors.full_messages
      redirect_to @object
    end
  end

  private
    def comment_params
      params.require(:comment).permit(:body, :commentable_type, :commentable_id)
    end
end

w5/w5d1/objective_setter_app/app/controllers/goals_controller.rb
class GoalsController < ApplicationController
  before_action :set_goal, only: [:show, :edit, :update, :destroy]
  before_action :ensure_login
  def index
    completed ||= params[:completed]
    @goals = Goal.where(goal_type: "public")
    query_filter = completed.nil? ? "1 = 1" : "completed = '#{completed}'"
    @my_goals = current_user.goals.where(query_filter)
    render :index
  end

  def new
    @goal = Goal.new
    render :new
  end

  def create
    @goal = Goal.new(goal_params)
    @goal.user = current_user

    if @goal.save
      redirect_to @goal
    else
      flash.now[:errors] = @goal.errors.full_messages
      render :new
    end
  end

  def show
    @comments = @goal.comments
    render :show
  end

  def edit
    render :edit
  end

  def update
    if @goal.update(goal_params)
      redirect_to goal_path(@goal)
    else
      flash.now[:errors] = @goal.errors.full_messages
      render :edit
    end
  end

  def complete
    @goal = Goal.find(params[:id])
    @goal.complete!
    redirect_to goals_path
  end

  private
    def goal_params
      params.require(:goal).permit(:title, :goal_type, :completed)
    end

    def set_goal
      @goal ||= Goal.find(params[:id])
    end
end

w5/w5d1/objective_setter_app/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    render :new
  end

  def create
    @user = User.find_by_credentials(session_params[:username], session_params[:password])

    if @user
      log_in!(@user)
      redirect_to root_path
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end

  def destroy
    log_out!
    redirect_to new_session_url
  end
  
  private
    def session_params
      params.require(:session).permit(:username, :password)
    end
end

w5/w5d1/objective_setter_app/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    render :new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      log_in!(@user)
      redirect_to root_path
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end

  def index

  end

  def show
    @comments = current_user.comments
    render :show
  end

  private
    def user_params
      params.require(:user).permit(:username, :password)
    end
end

w5/w5d1/objective_setter_app/app/helpers/application_helper.rb
module ApplicationHelper
  def authenticity_input
    "<input type=\"hidden\" name=\"authenticity_token\" value=\"#{form_authenticity_token}\">".html_safe
  end
end

w5/w5d1/objective_setter_app/app/helpers/comments_helper.rb
module CommentsHelper
end

w5/w5d1/objective_setter_app/app/helpers/goals_helper.rb
module GoalsHelper
end

w5/w5d1/objective_setter_app/app/helpers/sessions_helper.rb
module SessionsHelper
end

w5/w5d1/objective_setter_app/app/helpers/users_helper.rb
module UsersHelper
end

w5/w5d1/objective_setter_app/app/views/goals/edit.html.erb
<h1>Edit Goal</h1>

<form id="form_id" action="<%= goal_path(@goal) %>" method="post">
  <%= authenticity_input %>
  <input type="hidden" name="_method" value="patch">

  <input type="text" name="goal[title]" value="<%= @goal.title %>" id="title">
  <% Goal::GOAL_TYPES.each do |goal_type| %>
  <label>
    <%= goal_type %>
    <input type="radio" name="goal[goal_type]" value="<%= goal_type %>" id="goal_type" <%= "checked=checked" if goal_type == @goal.goal_type %>>
  </label>
  <% end %>

  <input type="submit" value="Update Goal">
</form>

w5/w5d1/objective_setter_app/app/views/goals/index.html.erb
<h1>All Goals</h1>
<h2>All public goals</h2>
<% @goals.each do |goal| %>
<p>
  <%= link_to goal.title, goal %>
</p>
<% end %>

<h2>All my goals</h2>
<% @my_goals.each do |goal| %>
<p>
  <%= link_to goal.title, goal %> |
  <%= goal.completed ? "completed" : "incomplete" %>
  <%= button_to "complete", complete_goal_path(goal), method: :patch %>
</p>
<% end %>

<%= link_to "Create New Goal", new_goal_path %>

w5/w5d1/objective_setter_app/app/views/goals/new.html.erb
<h1>New Goal</h1>

<form id="form_id" action="<%= goals_path %>" method="post">
  <%= authenticity_input %>
  <input type="text" name="goal[title]" value="" id="title">
  <% Goal::GOAL_TYPES.each do |goal_type| %>
  <label>
    <%= goal_type %>
    <input type="radio" name="goal[goal_type]" value="<%= goal_type %>" id="goal_type">
  </label>
  <% end %>
  <input type="submit" value="Create Goal">
</form>

w5/w5d1/objective_setter_app/app/views/goals/show.html.erb
<%= @goal.title %>
<%= link_to "Edit", edit_goal_path(@goal) %>
<ul>
<% @comments.each do |comment| %>
<li>
  <%= comment.body %> |
  <%= comment.commenter.username %>
</li>
<% end %>
</ul>

<%= render "comments/form", object: @goal %>