w4/w4d4/music_app/config/routes.rb
Rails.application.routes.draw do
  root to: "bands#index"

  resources :notes, only: [:create, :destroy]
  resources :tracks, except: [:new, :index]
  resources :albums, except: [:new, :index] do
    resources :tracks, only: :new
  end
  resources :bands do
    resources :albums, only: :new
  end
  resources :users do
    get "activate", on: :collection
  end
  resource :session
end

w4/w4d4/music_app/app/models/band.rb
# == Schema Information
#
# Table name: bands
#
#  id         :integer          not null, primary key
#  name       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Band < ActiveRecord::Base
  has_many :albums
  has_many :tracks, through: :albums
  validates :name, presence: true
end

w4/w4d4/music_app/app/controllers/bands_controller.rb
class BandsController < ApplicationController
  before_action :require_login
  def index
    @bands = Band.all
    render :index
  end

  def show
    @band = Band.find(params[:id])
    @albums = @band.albums
    render :show
  end

  def new
    @band = Band.new
    render :new
  end

  def edit
    @band = Band.find(params[:id])
    render :edit
  end

  def create
    @band = Band.new(band_params)

    if @band.save
      redirect_to @band, notice: 'Band was successfully created.'
    else
      flash.now[:errors] = @band.errors.full_messages
      render :new
    end
  end

  def update
    @band = Band.find(params[:id])

    if @band.update(band_params)
      redirect_to @band, notice: 'Band was successfully updated.'
    else
      flash.now[:errors] = @band.errors.full_messages
      render :edit
    end
  end

  def destroy
    @band = Band.find(params[:id])
    @band.destroy
    redirect_to bands_url, notice: 'Band was successfully destroyed.'
  end

  private
    def band_params
      params.require(:band).permit(:name)
    end
end

w4/w4d4/music_app/app/helpers/bands_helper.rb
module BandsHelper
end

w4/w4d4/music_app/app/views/bands/_form.html.erb
<% action = band.persisted? ? "edit" : "new" %>
<% form_action = band.persisted? ? "/bands/#{band.id}" : "/bands" %>
<% button_name = band.persisted? ? "Update Band" : "Create Band" %>

<form action="<%= form_action %>" method="post" class="form form-horizontal">
  <%= authenticity_input(form_authenticity_token) %>
  <%= method_override(action) %>

  <div class="form-group col-md-7">
    <label for="band_name" class="col-md-3 control-label">Band Name</label>
    <div class="col-md-4">
      <input type="text" name="band[name]" value="<%= band.name %>" id="band_name" class="form-control">
    </div>
  </div>

  <div class="form-group col-md-7">
    <div class="col-md-4 col-md-offset-3">
      <input type="submit" value="<%= button_name %>" class="btn btn-default">
    </div>
  </div>

</form>

w4/w4d4/music_app/app/views/bands/edit.html.erb
<h1>Editing Band</h1>
<div class="row">
  <%= render 'form', band: @band %>
</div>
<div class="row">
  <%= link_to 'Back', @band, class: "btn btn-default" %>
</div>

w4/w4d4/music_app/app/views/bands/index.html.erb
<div class="page-header">
  <h1>All Bands</h1>
</div>

<div class="row">
  <% @bands.each do |band| %>
  <div class="col-sm-3 col-md-3">
    <a href="<%= band_path(band) %>">
    <div class="thumbnail">
      <img src="http://placehold.it/175x175" alt="...">
      <div class="caption text-center">
        <h5><%= band.name %></h5></p>
      </div>
    </div></a>
  </div>
  <% end %>
</div>


<%= link_to 'New Band', new_band_path, class: "btn btn-success" %>

w4/w4d4/music_app/app/views/bands/new.html.erb
<div class="container">

  <h1 class="page-header">New Band</h1>

  <div class="row">
    <%= render 'form', band: @band %>
  </div>
  <div class="row">
    <%= link_to 'Back', bands_path %>
  </div>
</div>

w4/w4d4/music_app/app/views/bands/show.html.erb
<ol class="breadcrumb">
  <li class="active">
    <%= @band.name %>
  </li>
</ol>
<p>
  <strong>Name:</strong>
  <%= @band.name %>
</p>
<%= link_to 'Edit', edit_band_path(@band), class: "btn btn-primary" %>
<%= link_to "Delete", @band, class: "btn btn-danger", method: :delete, data: { confirm: "Are you sure?" } %>
<%= link_to 'Back to Bands', bands_path %>
<div class="row">
  <h5>Album List</h5>
  <ul>
    <% @albums.each do |album| %>
    <li>
      <%= link_to album.name, album %>
    </li>
    <% end %>
  </ul>
</div>


<%= link_to "New Album", new_band_album_path(@band), class: "btn btn-success" %>