w4/w4d5/reddit_clone/config/routes.rb
Rails.application.routes.draw do
  root to: 'subs#index'

  resources :users, only: [:new, :create]
  resource :session, only: [:new, :create, :destroy]
  resources :subs
  resources :posts, except: [:destroy]
  resources :comments, except: [:new, :edit, :update] do
    resources :comments, only: :new
  end
end

w4/w4d5/reddit_clone/app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :author, class_name: "User"
  belongs_to :commentable, polymorphic: true
  has_many(:child_comments,
            class_name: "Comment",
            foreign_key: :commentable_id,
            primary_key: :id,
            as: :commentable)

end

w4/w4d5/reddit_clone/app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id         :integer          not null, primary key
#  title      :string           not null
#  url        :string
#  content    :text
#  author_id  :integer          not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Post < ActiveRecord::Base
  belongs_to :author, class_name: "User"
  has_many :post_subs
  has_many :subs, through: :post_subs
  has_many :comments, as: :commentable

  validates :author_id, :title, presence: true
end

w4/w4d5/reddit_clone/app/models/post_sub.rb
# == Schema Information
#
# Table name: post_subs
#
#  id         :integer          not null, primary key
#  sub_id     :integer          not null
#  post_id    :integer          not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class PostSub < ActiveRecord::Base
  belongs_to :sub, inverse_of: :post_subs
  belongs_to :post, inverse_of: :post_subs

  validates :sub, :post, presence: true
end

w4/w4d5/reddit_clone/app/models/sub.rb
# == Schema Information
#
# Table name: subs
#
#  id           :integer          not null, primary key
#  title        :string           not null
#  description  :text
#  moderator_id :integer          not null
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#

class Sub < ActiveRecord::Base
  belongs_to :moderator, class_name: "User"
  has_many :post_subs
  has_many :posts, through: :post_subs

  validates :title, :moderator_id, presence: true
  validates :title, uniqueness: true


end

w4/w4d5/reddit_clone/app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  username        :string           not null
#  name            :string
#  password_digest :string           not null
#  session_token   :string           not null
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class User < ActiveRecord::Base
  attr_reader :password

  has_many :moderated_subs, class_name: "Sub", foreign_key: :moderator_id
  has_many :posts, foreign_key: :author_id
  has_many :posted_subs, through: :posts, source: :sub

  validates :username, :password_digest, presence: true
  validates :password, length: { minimum: 6, allow_nil: true }

  after_initialize :ensure_session_token

  def self.find_by_credentials(username, password)
    user = User.find_by(username: username)

    return nil unless user

    user.is_password?(password) ? user : nil
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def reset_session_token!
    self.session_token = SecureRandom.urlsafe_base64
    save!
    self.session_token
  end

  def ensure_session_token
    self.session_token ||= SecureRandom.urlsafe_base64
  end
end

w4/w4d5/reddit_clone/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user, :signed_in?

  def current_user
    User.find_by(session_token: session[:session_token])
  end

  def signed_in?
    !!current_user
  end

  def log_in!(user)
    session[:session_token] = user.reset_session_token!
  end

  def log_out!
    current_user.reset_session_token!
    session[:session_token] = nil
    redirect_to new_session_path
  end

  def ensure_logged_in

  end
end

w4/w4d5/reddit_clone/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def index
    @comments = Comment.where(commentable_type: "Post")
    render :index
  end

  def new
    @comment = Comment.new
    render :new
  end

  def create
    @comment = Comment.new(comment_params)
    @comment.author = current_user
  end

  def show
  end

  def destroy
  end

  private
    def comment_params
      params.require(:comment).permit(:content)
    end

end

w4/w4d5/reddit_clone/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def new
    @post = Post.new
    @all_subs = Sub.all
    render :new
  end

  def create
    @post = Post.new(post_params)
    @post.author = current_user

    if @post.save
      # @post.sub_ids = post_params[:sub_ids]
      redirect_to @post, notice: "Post Successfully Created"
    else
      flash.now[:error] = @post.errors.full_messages
      redirect_to @post.sub
    end
  end

  def show
    @post = Post.find(params[:id])
    @subs = @post.subs
    render :show
  end

  def edit
    @post = Post.find(params[:id])
    @all_subs = Sub.all

    render :edit
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      redirect_to @post, notice: "Update Succeeded"
    else
      flash.now[:error] = @post.errors.full_messages
      render :edit
    end
  end

  private
    def post_params
      params.require(:post).permit(:title, :content, :url, sub_ids: [])
    end
end

w4/w4d5/reddit_clone/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    render :new
  end

  def create
    @user = User.find_by_credentials(session_params[:username], session_params[:password])

    if @user
      log_in!(@user)
      redirect_to root_path
    else
      render :new
    end
  end

  def destroy
    log_out!
  end

  private

  def session_params
    params.require(:session).permit(:username, :password)
  end
end

w4/w4d5/reddit_clone/app/controllers/subs_controller.rb
class SubsController < ApplicationController
  def index
    @subs = Sub.all
    render :index
  end

  def new
    @sub = current_user.moderated_subs.new
  end

  def create
    @sub = current_user.moderated_subs.new(sub_params)

    if @sub.save
      redirect_to @sub
    else
      flash.now[:error] = @sub.errors.full_messages
      render :new
    end
  end

  def edit
    @sub = Sub.find(params[:id])
    render :edit
  end

  def update
    @sub = Sub.find(params[:id])

     if @sub.update(sub_params)
       redirect_to @sub
     else
       flash.now[:error] = @sub.errors.full_messages
       render :edit
     end
  end

  def destroy
    @sub = Sub.find(params[:id])
    @sub.destroy
    redirect_to subs_path
  end

  def show
    @sub = Sub.find(params[:id])
    @posts = @sub.posts
    @post = Post.new
    render :show
  end

  private
    def sub_params
      params.require(:sub).permit(:title, :description)
    end
end

w4/w4d5/reddit_clone/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    render :new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      log_in!(@user)
      redirect_to root_path, notice: "Successfully Created"
    else
      flash.now[:error] = @user.errors.full_messages
      render :new
    end
  end

  private
    def user_params
      params.require(:user).permit(:username, :password, :name)
    end
end

w4/w4d5/reddit_clone/app/helpers/application_helper.rb
module ApplicationHelper
  def authenticity_input(token)
    "<input type=\"hidden\" value=\"#{token}\" name=\"authenticity_token\">".html_safe
  end

  def bootstrap_class_for flash_type
    case flash_type
    when "notice"
      "alert-success"
    when "error"
      "alert-danger"
    when "alert"
      "alert-block"
    when "info"
      "alert-info"
    else
      flash_type.to_s
    end
  end
end

w4/w4d5/reddit_clone/app/helpers/subs_helper.rb
module SubsHelper
end

w4/w4d5/reddit_clone/app/views/layouts/_flash_messages.html.erb
<% flash.each do |type, message| %>
<div class="alert <%= bootstrap_class_for(type) %> fade in" role="alert">
  <button class="close" data-dismiss="alert">×</button>
  <%= message %>
</div>
<% end %>

w4/w4d5/reddit_clone/app/views/layouts/_greeting.html.erb
<% unless signed_in? %>
<form action="/session" method="post" class="form-inline">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

  <div class="form-group">
    <label class="sr-only" for="session_username">Username</label>
    <input type="text" name='session[username]' class="form-control" id="session_username" placeholder="Username">
  </div>
  <div class="form-group">
    <label class="sr-only" for="session_password">Password</label>
    <input type="password" name='session[password]' class="form-control" id="session_password" placeholder="Password">
  </div>
  <button type="submit" class="btn btn-default">Sign in</button>
  <%= link_to "Sign Up", new_user_url%>
</form>
<% else %>
<div class="welcome">
  <strong>Welcome <%= current_user.name %>!</strong>
  <%= button_to "Log Out", session_url, class: "btn btn-default",  method: :delete %>
</div>
<% end %>

w4/w4d5/reddit_clone/app/views/layouts/_nav.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">Reddit</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><a href="/subs">Subs <span class="sr-only">(current)</span></a></li>
        <li><%= link_to "New Post", new_post_path %></li>
        <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Dropdown <span class="caret"></span></a>
        <ul class="dropdown-menu" role="menu">
        <li><a href="#">Action</a></li>
        <li><a href="#">Another action</a></li>
        <li><a href="#">Something else here</a></li>
        <li class="divider"></li>
        <li><a href="#">Separated link</a></li>
        <li class="divider"></li>
        <li><a href="#">One more separated link</a></li>
      </ul>
    </li>
  </ul>
  <div class="navbar-form navbar-right">
    <%= render partial: "layouts/greeting" %>
  </div>
</div><!-- /.navbar-collapse -->
</div><!-- /.container-fluid -->

</nav>

w4/w4d5/reddit_clone/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Reddit</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootswatch/3.3.1/paper/bootstrap.min.css">
  <!-- Latest compiled and minified JavaScript -->
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/js/bootstrap.min.js"></script>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render "layouts/nav"%>
  <%= render "layouts/flash_messages", flash: flash %>
  <div class="container">
    <%= yield %>
  </div>

</body>
</html>

w4/w4d5/reddit_clone/app/views/subs/_form.html.erb
<% request_method = sub.persisted? ? 'patch' : 'post' %>
<% action = sub.persisted? ? "/subs/#{sub.id}" : "/subs" %>
<% submit_value = sub.persisted? ? 'Update sub!' : 'New sub!' %>

<form action="<%= action %>" method="post" class="form-horizontal">
  <input type="hidden" name="_method" value="<%= request_method %>">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <div class="form-group">
    <label for="sub_title" class="col-md-2 control-label">Title</label>
    <div class="col-md-6">
      <input type="text" name="sub[title]" value="<%= sub.title %>" id="sub_title">
    </div>
  </div>

  <div class="form-group">
    <label for="sub_desciption" class="col-md-2 control-label">Description</label>
    <div class="col-md-6">
      <textarea class="form-control" name="sub[description]" id="sub_desciption" rows="5"><%= sub.description %></textarea>
    </div>
  </div>

  <div class="form-group">
    <div class="col-md-6 col-md-offset-2">
      <input type="submit" class="btn btn-default" value="<%= submit_value %>">
    </div>
  </div>
</form>

w4/w4d5/reddit_clone/app/views/subs/edit.html.erb
<h1>Edit Sub</h1>

<div class="row">
  <%= render "form", sub: @sub %>
</div>

<div class="row">
  <%= link_to "Back", @sub, class: "btn btn-default" %>
  <%= link_to "Delete", @sub, class: "btn btn-danger", method: :delete, data: { confirm: "Are you sure?" } %>
</div>

w4/w4d5/reddit_clone/app/views/subs/index.html.erb
<h1>All Subs</h1>

<%= link_to "New Sub", new_sub_path, class: "btn btn-primary" %>

<div class="row">
  <ul>
    <% @subs.each do |sub| %>
      <li>
        <%= link_to sub.title, sub %>
      </li>
    <% end %>
  </ul>
</div>

w4/w4d5/reddit_clone/app/views/subs/new.html.erb
<h1>New Sub</h1>

<div class="row">
  <%= render "form", sub: @sub %>
</div>
<div class="row">
  <%= link_to "Back", @sub, class: "btn btn-default" %>
</div>

w4/w4d5/reddit_clone/app/views/subs/show.html.erb
<ol class="breadcrumb">
  <li class="active">
    <%= link_to "All Subs", subs_path %>
  </li>
</ol>


<h1>
  <%= @sub.title %> | <small>Moderator : <%= @sub.moderator.name %></small>
  <%= link_to "Edit", edit_sub_path(@sub), class: "btn btn-primary" %>
</h1>
<p>
  <%= @sub.description %>
</p>

<div class="row">
  <h4>Posts</h4>
  <ul>
    <% @posts.each do |post| %>
      <li><%= link_to post.title, post %></li>
    <% end %>
  </ul>

</div>